### ISSUE TITLE
Optional iconv on require

### ISSUE THREAD

**Issue by jkoudys** [andris9/node-gettext#18]
I'm using this as part of a ReactJS project to provide both server and client side translations. Since there's a binary lib with iconv, browserify will die terribly while building its dependencies.

I see that gettext-parser is using the pure-js iconv-lite, so I'm using that for the time being to build an object from my .mo client-side, but that's really the opposite of what's most useful: client side translations functions, and server-side parsing (since then I could just convert my MOs to json when I deploy and use those).

I think what might be best is if we could choose a 'lite' version, e.g.

```
require Gettext = require('node-gettext/lite');
```

What do you think? I'm fine implementing it and giving a PR if you think this makes sense, but maybe you have a different direction in mind for how node-gettext + gettext-parser divide their responsibilities.

**Comment by ArnaudRinquin** [comment]
+1 on that one. `iconv-lite` is more than enough in most cases.

**Comment by ArmorDarks** [comment]
I have feeling that using `node-gettext` on client side is quite wrong direction. Though, I may be wrong.

**Comment by andris9** [comment]
Yeah, this is a node, not client module but you check out a demo I once made: [webgettext](https://github.com/andris9/webgettext)
