### ISSUE TITLE
Object #<Gettext> has no method 'setTranslation'

### ISSUE THREAD

**Issue by evilaliv3** [andris9/node-gettext#20]
While working on GlobaLeaks project and updating to latest node-gettext release i'm getting the following error while using the setTranslation function:

    Warning: Object #<Gettext> has no method 'setTranslation' Use --force to continue.

what i'm performing is simply a setTranslation call on the gettext object used exaclty as explained on https://github.com/andris9/node-gettext/blob/master/README.md

here you can see the relevant code used, but from a grep it seems that the function has simply been removed. probably the documentation is simply missing to be updated?
https://github.com/globaleaks/GlobaLeaks/blob/devel/client/Gruntfile.js#L423

**Comment by andris9** [comment]
Yes, this method (and lot others) were removed in the 1.0 release. If you still need these, use the 0.2.14 version of node-gettext. The 0.2 version used its own handlers for *mo* and *po* files but 1.0 is mostly just a convinience wrapper around [gettext-parser](https://github.com/andris9/gettext-parser). If you want to compose *mo* and *po* files, I'd suggest using that module instead.

**Comment by evilaliv3** [comment]
great thanks.

\cc @hellais
