### ISSUE TITLE
Adding of few language files per one domain

### ISSUE THREAD

**Issue by ArmorDarks** [andris9/node-gettext#22]
First of all, thanks for great tools!

Sometimes applications are quite large, thus developers splitting single `message.po` into specific `.po` per each component.

Hower, current declaration doesn't allow to declare few `.po` files per single domain:

```
gt.addTextdomain("et", [file1, file2]) // won't work;
```

And there is no easy way around to concatenate `.po` files due to their structure.

Is there any chances for adding of that feature? Or maybe I'm doing it in wrong way?

**Comment by pablonazareno** [comment]
I have the same requirement.
Are you planning this feature?

**Comment by andris9** [comment]
Merging different translation files is a complex task and out of scope for this module. Use the standard gettext utility `msgmerge` for it

     msgmerge old.po new.po -o merged.po

**Comment by ArmorDarks** [comment]
Thanks for your reply.

Ah, I see. Didn't think at first place that merging of `.po` files isn't that simple.

I hope that one day node community will see `node-msgmerge` too :)

**Comment by ArmorDarks** [comment]
Now, after realizing how domains actually have to be used (https://github.com/andris9/node-gettext/issues/24), I've understood that merging isn't what we need here.

Actually, instead of `addTextdomain` we need something like that:

``` coffee
gt.addLocaleData('et', [`messages.po`, `file2.po`])
```

Which will create locale `et` with domains `messages` and `files2`

They should be accessed as follwing:

``` coffee
gettext('String from messages') # load from default domain (usually 'messages')
dgettext('messages', 'String from messages') # same as above
dgettext('file2', 'String from file2')
```

`addTextDomain` will instead populate existing locale with new domains:

``` coffee
gt.addTextdomain('et', 'newDomainName')
```

**Comment by ArmorDarks** [comment]
Just for the information, we've implemented hacky way in [Kotsu](https://github.com/LotusTM/Kotsu) to handle locales and domains via same argument here: https://github.com/LotusTM/Kotsu/commit/c0f1ec0f001120c6b707a6de29b36269027f8cc1

It isn't resolution for this issue, since it's improper way to handle domains and locales. But it's better than nothing.

Maybe it will help someone with same issue.

**Comment by firebird631** [comment]
I'm looking for a way to update the domain with many **po** file too. So I've just modified **addTextdomain** to update if the translation object exists but I'm not sur its a correct way because of some metadata like the headers. I could _msgcat_ all my **po** files to a single file but it is less flexible in the management of my project.

**Comment by ArmorDarks** [comment]
@firebird631 It depends on what exactly you want to achieve. First of all, I recommend to read this issue https://github.com/andris9/node-gettext/issues/24

You will see, that `node-gettext` wrongly uses domains for locales. In gettext you should have locale, which could have default domain, and as much as you need additional domains (usually standalone files represents specific domain in locale).

If you just need to have single, large, merged file from other files — just use `msgmerge` and feed to `addTextdomain` merged file.

However, if you need to have separate files in one locale, to access them separately, so far you don't have other options except using hack, implemented in Kostu and mentioned by me in that comment https://github.com/andris9/node-gettext/issues/22#issuecomment-149530888

This will allow you to access domains in following manner: https://github.com/LotusTM/Kotsu/blob/master/source/layouts/index.nj#L78
